# https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "greenwood-demo-platform-cloudflare"
pages_build_output_dir = "./public"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

# TODO - seems like this can only be done through the UI
# https://developers.cloudflare.com/workers/wrangler/custom-builds
# [build]
# command = "npm run build"