# https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "greenwood-demo-platform-cloudflare"
pages_build_output_dir = "./public"
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2024-09-23"
# https://github.com/cloudflare/workers-sdk/issues/6434
# no_bundle = true

# TODO - seems like this can only be done through the UI
# https://developers.cloudflare.com/workers/wrangler/custom-builds
# [build]
# command = "npm run build"